{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fMetas\",\"fVendas\",\"Consulta2\",\"dCalendario\",\"dVendedor\",\"dProduto\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1203.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Consulta2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let\r",
          "    Origen = List.Dates\r",
          "in\r",
          "    Origen"
        ],
        "kind": "m",
        "lineageTag": "322e3803-0cf6-4717-b7e1-bd5c5c655efa"
      }
    ],
    "relationships": [
      {
        "name": "39af6c1f-fbeb-17b9-edb7-9b0b8407c9d3",
        "fromColumn": "DataEmissao",
        "fromTable": "fVendas",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "5b46dfef-0d10-394b-65a0-18d4fdc3c162",
        "fromColumn": "Atributo",
        "fromTable": "fMetas",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "AutoDetected_5a25eb5e-c006-45aa-a7b2-40391e129fb5",
        "fromColumn": "cdProduto",
        "fromTable": "fVendas",
        "toColumn": "cdProduto",
        "toTable": "dProduto"
      },
      {
        "name": "AutoDetected_f1315362-261e-4186-94d2-a76faf0d041a",
        "fromColumn": "cdVendedor",
        "fromTable": "fVendas",
        "toColumn": "cdVendedor",
        "toTable": "dVendedor"
      }
    ],
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "fMetas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cdVendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9cbc440-a4af-487b-9699-0dc0bc6108f6",
            "sourceColumn": "cdVendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "5b55816f-990b-4dda-841a-9510b2727ae2",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          },
          {
            "name": "Atributo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "286fe1c3-66fb-442b-a4d8-7d2ad2a0a46d",
            "sourceColumn": "Atributo",
            "summarizeBy": "none"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "d8906e4e-cae5-4138-b773-b79522395286",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "00054e4a-4fef-4829-8e86-e328e48495b1",
        "partitions": [
          {
            "name": "fMetas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\Gabriel\\OneDrive\\DEV\\Estudos B.I\\Curso Express - Xperiun\\Portfolio1\\Metas.xlsx\"), null, true),",
                "    Metas_Sheet = Origen{[Item=\"Metas\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Metas_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"Metas por Vendedor\", type any}, {\"Column2\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}}),",
                "    #\"Encabezados promovidos1\" = Table.PromoteHeaders(#\"Tipo cambiado\", [PromoteAllScalars=true]),",
                "    #\"Filas superiores quitadas\" = Table.Skip(#\"Encabezados promovidos1\",2),",
                "    #\"Encabezados promovidos2\" = Table.PromoteHeaders(#\"Filas superiores quitadas\", [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Encabezados promovidos2\",{{\"cdVendedor\", type any}, {\"01/01/2017\", type number}, {\"01/02/2017\", type number}, {\"01/03/2017\", type number}, {\"01/04/2017\", type number}, {\"01/05/2017\", type number}, {\"01/06/2017\", type number}, {\"01/07/2017\", type number}, {\"01/08/2017\", type number}, {\"01/09/2017\", type number}, {\"01/10/2017\", type number}, {\"01/11/2017\", type number}, {\"01/12/2017\", type number}, {\"01/01/2018\", type number}, {\"01/02/2018\", type number}, {\"01/03/2018\", type number}, {\"01/04/2018\", type number}, {\"01/05/2018\", type number}, {\"01/06/2018\", type number}, {\"01/07/2018\", type number}, {\"01/08/2018\", type number}, {\"01/09/2018\", type number}, {\"01/10/2018\", type number}, {\"01/11/2018\", type number}, {\"01/12/2018\", type number}, {\"Total\", type number}}),",
                "    #\"Columna de anulación de dinamización\" = Table.UnpivotOtherColumns(#\"Tipo cambiado1\", {\"cdVendedor\", \"Total\"}, \"Atributo\", \"Valor\"),",
                "    #\"Tipo cambiado2\" = Table.TransformColumnTypes(#\"Columna de anulación de dinamización\",{{\"Atributo\", type date}, {\"Total\", Currency.Type}, {\"Valor\", Currency.Type}}),",
                "    #\"Columnas reordenadas\" = Table.ReorderColumns(#\"Tipo cambiado2\",{\"cdVendedor\", \"Atributo\", \"Total\", \"Valor\"}),",
                "    #\"Tipo cambiado3\" = Table.TransformColumnTypes(#\"Columnas reordenadas\",{{\"Valor\", type number}, {\"Total\", Currency.Type}}),",
                "    #\"Duplicados quitados\" = Table.Distinct(#\"Tipo cambiado3\", {\"Valor\"})",
                "in",
                "    #\"Duplicados quitados\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ef243d92-9f0f-4d4d-a667-29c6fcc74ebc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4cf8f77c-dec7-4bc8-8664-11acc340cde5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "66d92b8e-8334-474e-ba5b-dab2f6fb450b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bd77f2e1-82f8-4f5c-8f86-67666e08dbff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "99e7e153-2a17-40c8-a9ba-6e590cb4bd12",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7f5cdbb8-c1ae-4319-a01a-8107388ba6f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "ad0c5438-88bd-410a-bca7-c9bc324a8f3d",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "131b3a9d-2866-4e1d-a696-c6af287c0369",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "c993c58d-4caa-4b01-b8c2-cced463cd9a1",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9b7e9dc0-c4a1-4616-b08e-5c24bc1da2d6",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "040a3ecf-41aa-4ee1-a9cd-12c627e2e492",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "7ee07c63-2b7a-450b-8f39-71e3236b211b",
                "ordinal": 3
              }
            ],
            "lineageTag": "6f29c19a-4666-4589-954a-ac862dd04ded"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "8e32497c-4780-44c4-8f17-927457da40b5",
        "partitions": [
          {
            "name": "DateTableTemplate_ef243d92-9f0f-4d4d-a667-29c6fcc74ebc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fVendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataEmissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "504e7e2f-39b6-4c0b-bd55-b6c18458ed6b",
            "sourceColumn": "DataEmissao",
            "summarizeBy": "none"
          },
          {
            "name": "NFe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a386006f-bf93-40c3-b155-972f252e23c5",
            "sourceColumn": "NFe",
            "summarizeBy": "sum"
          },
          {
            "name": "cdProduto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70987dac-d0f1-4bdf-9cbe-b9000e6ce123",
            "sourceColumn": "cdProduto",
            "summarizeBy": "none"
          },
          {
            "name": "cdVendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5483ac7-f4dd-4041-82e4-17fbb399e144",
            "sourceColumn": "cdVendedor",
            "summarizeBy": "none"
          },
          {
            "name": "QtdItens",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "387ecdba-af09-4614-8941-3180e74ec811",
            "sourceColumn": "QtdItens",
            "summarizeBy": "sum"
          },
          {
            "name": "ValorUnitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "ad1a8680-0527-4b1b-9838-3a4c01c6d5c8",
            "sourceColumn": "ValorUnitario",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ac276910-e73a-4996-aec9-f5bf44f40ea1",
        "partitions": [
          {
            "name": "fVendas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\Gabriel\\OneDrive\\DEV\\Estudos B.I\\Curso Express - Xperiun\\Portfolio1\\Vendas.xlsx\"), null, true),",
                "    Planilha1_Sheet = Origen{[Item=\"Planilha1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"DataEmissao\", type date}, {\"NFe\", Int64.Type}, {\"cdProduto\", Int64.Type}, {\"Produto\", type text}, {\"Grupo Produto\", type text}, {\"Linha Produto\", type text}, {\"cdVendedor\", Int64.Type}, {\"Vendedor\", type text}, {\"Supervisor\", type text}, {\"Gerente\", type text}, {\"Equipe Vendas\", type text}, {\"QtdItens\", Int64.Type}, {\"ValorUnitario\", Currency.Type}}),",
                "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Tipo cambiado\",{\"DataEmissao\", \"NFe\", \"cdProduto\", \"cdVendedor\", \"QtdItens\", \"ValorUnitario\"})",
                "in",
                "    #\"Otras columnas quitadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96b6de8c-3dce-4a75-9721-b5ebfe7f2033",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64736d66-3f82-4fc3-8093-f1d5532ef7d6",
            "sourceColumn": "Año",
            "summarizeBy": "sum"
          },
          {
            "name": "Nombre del mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1bf70a6-8582-48fb-8195-7c58b76d6801",
            "sourceColumn": "Nombre del mes",
            "summarizeBy": "none"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5fdada8-df21-47f1-b2e4-33b713fce5b6",
            "sourceColumn": "Mes",
            "summarizeBy": "sum"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "77f3ded5-9154-41c0-86c8-88443cf5f9a0",
            "sourceColumn": "Trimestre",
            "summarizeBy": "sum"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9fbc8780-0218-4541-bc8f-e50005a666df",
            "sourceColumn": "Día",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e0157b5e-1a2c-4e18-8666-cf9a5155ee88",
        "partitions": [
          {
            "name": "dCalendario",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Consulta2(#date(2017, 1, 1), 1200, #duration(1, 0, 0, 0)),",
                "    #\"Convertida en tabla\" = Table.FromList(Origen, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Año insertado\" = Table.AddColumn(#\"Convertida en tabla\", \"Año\", each Date.Year([Column1]), Int64.Type),",
                "    #\"Mes insertado\" = Table.AddColumn(#\"Año insertado\", \"Mes\", each Date.Month([Column1]), Int64.Type),",
                "    #\"Nombre del mes insertado\" = Table.AddColumn(#\"Mes insertado\", \"Nombre del mes\", each Date.MonthName([Column1]), type text),",
                "    #\"Columnas reordenadas\" = Table.ReorderColumns(#\"Nombre del mes insertado\",{\"Column1\", \"Año\", \"Nombre del mes\", \"Mes\"}),",
                "    #\"Trimestre insertado\" = Table.AddColumn(#\"Columnas reordenadas\", \"Trimestre\", each Date.QuarterOfYear([Column1]), Int64.Type),",
                "    #\"Día del año insertado\" = Table.AddColumn(#\"Trimestre insertado\", \"Día del año\", each Date.DayOfYear([Column1]), Int64.Type),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Día del año insertado\",{\"Día del año\"}),",
                "    #\"Día de la semana insertado\" = Table.AddColumn(#\"Columnas quitadas\", \"Día de la semana\", each Date.DayOfWeek([Column1]), Int64.Type),",
                "    #\"Columnas quitadas1\" = Table.RemoveColumns(#\"Día de la semana insertado\",{\"Día de la semana\"}),",
                "    #\"Día insertado\" = Table.AddColumn(#\"Columnas quitadas1\", \"Día\", each Date.Day([Column1]), Int64.Type),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Día insertado\",{{\"Column1\", \"Data\"}})",
                "in",
                "    #\"Columnas con nombre cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dVendedor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cdVendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "966d305e-1399-4ec1-8dac-44a01192cca4",
            "sourceColumn": "cdVendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85a6fa61-4059-4e72-b013-c1179eed206e",
            "sourceColumn": "Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Supervisor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b241624-380e-461e-bc7a-0a92973eab15",
            "sourceColumn": "Supervisor",
            "summarizeBy": "none"
          },
          {
            "name": "Gerente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86a62112-20b4-4f4f-b5a0-6eb991ffc1ee",
            "sourceColumn": "Gerente",
            "summarizeBy": "none"
          },
          {
            "name": "Equipe Vendas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbff242e-853f-421c-b570-a8875d27ad7a",
            "sourceColumn": "Equipe Vendas",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "32f26e78-4e3b-480b-97ca-8b840e82bad4",
        "partitions": [
          {
            "name": "dVendedor",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\Gabriel\\OneDrive\\DEV\\Estudos B.I\\Curso Express - Xperiun\\Portfolio1\\Vendas.xlsx\"), null, true),",
                "    Planilha1_Sheet = Origen{[Item=\"Planilha1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"DataEmissao\", type date}, {\"NFe\", Int64.Type}, {\"cdProduto\", Int64.Type}, {\"Produto\", type text}, {\"Grupo Produto\", type text}, {\"Linha Produto\", type text}, {\"cdVendedor\", Int64.Type}, {\"Vendedor\", type text}, {\"Supervisor\", type text}, {\"Gerente\", type text}, {\"Equipe Vendas\", type text}, {\"QtdItens\", Int64.Type}, {\"ValorUnitario\", Currency.Type}}),",
                "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Tipo cambiado\",{\"cdVendedor\", \"Vendedor\", \"Supervisor\", \"Gerente\", \"Equipe Vendas\"}),",
                "    #\"Duplicados quitados\" = Table.Distinct(#\"Otras columnas quitadas\", {\"cdVendedor\"}),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Duplicados quitados\",{{\"cdVendedor\", type text}})",
                "in",
                "    #\"Tipo cambiado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dProduto",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cdProduto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85141819-df41-40b4-8b19-177118fca88b",
            "sourceColumn": "cdProduto",
            "summarizeBy": "none"
          },
          {
            "name": "Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4eb6177d-8c6c-433d-9d99-cdb9b6b9c8e6",
            "sourceColumn": "Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Grupo Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9548f160-f21c-4250-b8e3-e8c4f8909cb4",
            "sourceColumn": "Grupo Produto",
            "summarizeBy": "none"
          },
          {
            "name": "Linha Produto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd74ff8e-72c6-4e5c-8135-dfaa04859d6b",
            "sourceColumn": "Linha Produto",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5849e6c5-f0cd-44e3-8b97-0af38d6994bb",
        "partitions": [
          {
            "name": "dProduto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\Gabriel\\OneDrive\\DEV\\Estudos B.I\\Curso Express - Xperiun\\Portfolio1\\Vendas.xlsx\"), null, true),",
                "    Planilha1_Sheet = Origen{[Item=\"Planilha1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"DataEmissao\", type date}, {\"NFe\", Int64.Type}, {\"cdProduto\", Int64.Type}, {\"Produto\", type text}, {\"Grupo Produto\", type text}, {\"Linha Produto\", type text}, {\"cdVendedor\", Int64.Type}, {\"Vendedor\", type text}, {\"Supervisor\", type text}, {\"Gerente\", type text}, {\"Equipe Vendas\", type text}, {\"QtdItens\", Int64.Type}, {\"ValorUnitario\", Currency.Type}}),",
                "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Tipo cambiado\",{\"cdProduto\", \"Produto\", \"Grupo Produto\", \"Linha Produto\"}),",
                "    #\"Duplicados quitados\" = Table.Distinct(#\"Otras columnas quitadas\", {\"cdProduto\"})",
                "in",
                "    #\"Duplicados quitados\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}